BrewDayAPP/Controllers/IngredientRecipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BrewDayAPP;

namespace BrewDayAPP.Controllers
{
    public class IngredientRecipesController : Controller
    {
        private BrewDayDBEntities db = new BrewDayDBEntities();

        // GET: IngredientRecipes con parametro di ingresso id della ricetta
        public ActionResult Index(int? recipiesID)
        {
            var ingredientRecipe=db.IngredientRecipe.Include(i => i.Recipies);
            return View(ingredientRecipe.Where(x=>x.IdRecipes==recipiesID));
        }

        // GET: IngredientRecipes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngredientRecipe ingredientRecipe = db.IngredientRecipe.Find(id);
            if (ingredientRecipe == null)
            {
                return HttpNotFound();
            }
            return View(ingredientRecipe);
        }

        // GET: IngredientRecipes/Create
        public ActionResult Create(int? recipiesID)
        {
            ViewBag.IdIngredients = new SelectList(db.Ingredients, "ID", "Description");
            ViewBag.IdRecipes = new SelectList(db.Recipies.Where(x=>x.ID==recipiesID), "ID", "Description");
            return View();
        }

        // POST: IngredientRecipes/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IdRecipes,IdIngredients,AbsolutQuantity,AbsolutUnitMeasure")] IngredientRecipe ingredientRecipe)
        {
            if (ModelState.IsValid)
            {
                db.IngredientRecipe.Add(ingredientRecipe);
                db.SaveChanges();
                return RedirectToAction("Index", "Recipies");
            }

            ViewBag.IdIngredients = new SelectList(db.Ingredients, "ID", "Description", ingredientRecipe.IdIngredients);
            ViewBag.IdRecipes = new SelectList(db.Recipies, "ID", "Description", ingredientRecipe.IdRecipes);
            return View(ingredientRecipe);
        }

        // GET: IngredientRecipes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngredientRecipe ingredientRecipe = db.IngredientRecipe.Find(id);
            if (ingredientRecipe == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdIngredients = new SelectList(db.Ingredients, "ID", "Description", ingredientRecipe.IdIngredients);
            ViewBag.IdRecipes = new SelectList(db.Recipies, "ID", "Description", ingredientRecipe.IdRecipes);
            return View(ingredientRecipe);
        }

        // POST: IngredientRecipes/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IdRecipes,IdIngredients,AbsolutQuantity,AbsolutUnitMeasure")] IngredientRecipe ingredientRecipe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ingredientRecipe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Recipies");
            }
            ViewBag.IdIngredients = new SelectList(db.Ingredients, "ID", "Description", ingredientRecipe.IdIngredients);
            ViewBag.IdRecipes = new SelectList(db.Recipies, "ID", "Description", ingredientRecipe.IdRecipes);
            return View(ingredientRecipe);
        }

        // GET: IngredientRecipes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngredientRecipe ingredientRecipe = db.IngredientRecipe.Find(id);
            if (ingredientRecipe == null)
            {
                return HttpNotFound();
            }
            return View(ingredientRecipe);
        }

        // POST: IngredientRecipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IngredientRecipe ingredientRecipe = db.IngredientRecipe.Find(id);
            db.IngredientRecipe.Remove(ingredientRecipe);
            db.SaveChanges();
            return RedirectToAction("Index", "Recipies");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BrewDayAPP/Controllers/RecipiesController.cs
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace BrewDayAPP.Controllers
{
    public class RecipiesController : Controller
    {
        private BrewDayDBEntities db = new BrewDayDBEntities();

        // GET: Recipies
        public ActionResult Index()
        {
            var recipies = db.Recipies.Include(r => r.AspNetUsers);
            var userID = User.Identity.GetUserId();
            if (User.Identity.GetUserName().Equals(ConfigurationManager.AppSettings["SuperUser"]))
            {
                //visualizza tutto
                return View(recipies.ToList());
            }
            else
            {   
                //filtra in base all'utente loggato
                return View(recipies.Where(x => x.UserId == userID).ToList());
            }

        }

        // GET: Recipies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Recipies recipies = db.Recipies.Find(id);
            if (recipies == null)
            {
                return HttpNotFound();
            }
            return View(recipies);
        }

        // GET: Recipies/Create
        public ActionResult Create()
        {
            var userID = User.Identity.GetUserId();
            if (User.Identity.GetUserName().Equals(ConfigurationManager.AppSettings["SuperUser"]))
            {
                ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            }
            else
            {
                ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x => x.Id == userID), "Id", "Email");
            }
            return View();
        }

        // POST: Recipies/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description,Rate,UserId")] Recipies recipies)
        {
            if (ModelState.IsValid)
            {
                db.Recipies.Add(recipies);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", recipies.UserId);
            return View(recipies);
        }

        // GET: Recipies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipies recipies = db.Recipies.Find(id);
            if (recipies == null)
            {
                return HttpNotFound();
            }
            var userID = User.Identity.GetUserId();
            if (User.Identity.GetUserName().Equals(ConfigurationManager.AppSettings["SuperUser"]))
            {
                ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", recipies.UserId);
            }
            else
            {
                ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x => x.Id == userID), "Id", "Email", recipies.UserId);
            }
            return View(recipies);
        }

        // POST: Recipies/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description,Rate,UserId")] Recipies recipies)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recipies).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", recipies.UserId);
            return View(recipies);
        }

        // GET: Recipies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipies recipies = db.Recipies.Find(id);
            if (recipies == null)
            {
                return HttpNotFound();
            }
            return View(recipies);
        }

        // POST: Recipies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipies recipies = db.Recipies.Find(id);
            //cancella tutti gli ingredienti correlati
            var items = db.IngredientRecipe.Where(item => item.IdRecipes == id);
            foreach (var item in items)
                db.IngredientRecipe.Remove(item);

            db.Recipies.Remove(recipies);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BrewDayAPP/Views/Recipies/Create.cshtml
@model BrewDayAPP.Recipies

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Recipies</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BrewDayAPP/Views/Recipies/Delete.cshtml
@model BrewDayAPP.Recipies

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipies</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BrewDayAPP/Views/Recipies/Details.cshtml
@model BrewDayAPP.Recipies

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Recipies</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

    </dl>
</div>
<table>
    @foreach (var item in Model.IngredientRecipe)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AbsolutQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AbsolutUnitMeasure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdIngredients)
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BrewDayAPP/Views/Recipies/Edit.cshtml
@model BrewDayAPP.Recipies

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Recipies</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BrewDayAPP/Views/Recipies/Index.cshtml
@model IEnumerable<BrewDayAPP.Recipies>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        string selectedRow = "";
        if (item.ID == ViewBag.ID)
        {
            selectedRow = "success";

        }
        <tr class="@selectedRow">

            <td>
                @*@Html.ActionLink("Select", "Index", new { ID = item.ID })*@
                @*@Html.ActionLink("Select", "Index", "IngredientRecipes", new { recipiesID = item.ID })*@
                @Html.ActionLink("Select", "Index",new { Controller = "IngredientRecipes", action = "Index", recipiesID = item.ID })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUsers.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>