BrewDayAPP/Controllers/BrewsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BrewDayAPP;
using Microsoft.AspNet.Identity;

namespace BrewDayAPP.Controllers
{
    public class BrewsController : Controller
    {
        private BrewDayDBEntities db = new BrewDayDBEntities();

        // GET: Brews
        public ActionResult Index()
        {
            var brews = db.Brews.Include(b => b.AspNetUsers).Include(b => b.Recipies);
            var userID = User.Identity.GetUserId();
            if (User.Identity.GetUserName().Equals(ConfigurationManager.AppSettings["SuperUser"]))
            {
                return View(brews.ToList());
            }
            else
            {
                return View(brews.Where(x=>x.UserId==userID).ToList());
            }
                
        }

        // GET: Brews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brews brews = db.Brews.Find(id);
            if (brews == null)
            {
                return HttpNotFound();
            }
            return View(brews);
        }

        // GET: Brews/Create
        public ActionResult Create()
        {
            var userID = User.Identity.GetUserId();
            if (User.Identity.GetUserName().Equals(ConfigurationManager.AppSettings["SuperUser"]))
            {
                ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
                ViewBag.IdRecipies = new SelectList(db.Recipies, "ID", "Description");
            }
            else
            {
                ViewBag.UserId = new SelectList(db.AspNetUsers.Where(x=>x.Id==userID), "Id", "Email");
                ViewBag.IdRecipies = new SelectList(db.Recipies.Where(x=>x.UserId==userID), "ID", "Description");
            }
            return View();
        }

        // POST: Brews/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description,IdRecipies,BatchSize,Notes,DateBrew,UserId")] Brews brews)
        {
            if (ModelState.IsValid)
            {
                //recupera dal model parametri che mi servono per la spUpdateQuantityIngredients
                var recipiesId = brews.IdRecipies;
                var batchSize = brews.BatchSize;

                //lancia la spUpdateQuantityIngredients
                var connection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
                var command = new SqlCommand("spUpdateQuantityIngredients", connection);
                command.CommandType = CommandType.StoredProcedure;
                command.Parameters.AddWithValue("@recipiesId", recipiesId);
                command.Parameters.AddWithValue("@batchSize", batchSize);
                connection.Open();
                command.ExecuteNonQuery();
                connection.Close();

                //lancia inserimento di un nuovo record per Brews
                db.Brews.Add(brews);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", brews.UserId);
            ViewBag.IdRecipies = new SelectList(db.Recipies, "ID", "Description", brews.IdRecipies);
            return View(brews);
        }

        // GET: Brews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brews brews = db.Brews.Find(id);
            if (brews == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", brews.UserId);
            ViewBag.IdRecipies = new SelectList(db.Recipies, "ID", "Description", brews.IdRecipies);
            return View(brews);
        }

        // POST: Brews/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description,IdRecipies,BatchSize,Notes,DateBrew,UserId")] Brews brews)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brews).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", brews.UserId);
            ViewBag.IdRecipies = new SelectList(db.Recipies, "ID", "Description", brews.IdRecipies);
            return View(brews);
        }

        // GET: Brews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brews brews = db.Brews.Find(id);
            if (brews == null)
            {
                return HttpNotFound();
            }
            return View(brews);
        }

        // POST: Brews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brews brews = db.Brews.Find(id);
            db.Brews.Remove(brews);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BrewDayAPP/Controllers/IngredientsToSubstractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrewDayAPP.Controllers
{
    public class IngredientsToSubstractController : Controller
    {
        // GET: IngredientToSubstract
        public ActionResult _Index(int? recipiesID, int batchSize)
        {
            BrewDayDBEntities db = new BrewDayDBEntities();
            string query = "select r.ID as IdRecipie, i.ID as IdIngredient, i.[Description], i.UnitMeasure, i.Quantity, ir.AbsolutQuantity, " + batchSize + " as [Batchsize], (ir.AbsolutQuantity * " + batchSize + ") as QuantityToSubstract, (i.Quantity - (ir.AbsolutQuantity * " + batchSize + ")) as QuantityAfterBrew, i.Threshold" +
                                                                        " from Ingredients as i inner join" +
                                                                        " IngredientRecipe ir on i.ID = ir.IdIngredients inner join" +
                                                                        " Recipies as r on ir.IdRecipes = r.ID " +
                                                                        " where r.ID =" + recipiesID +
                                                                        " group by r.ID, i.ID, i.[Description], i.UnitMeasure, i.Quantity, ir.AbsolutQuantity, i.Threshold";
            IEnumerable<IngredientToSubstract> data = db.Database.SqlQuery<IngredientToSubstract>(query);
            return PartialView(data.ToList());
        }

    }
}

BrewDayAPP/Views/Brews/Create.cshtml
@model BrewDayAPP.Brews

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">
   
    $(document).ready(function () {
        $("#IdRecipies").change(function () {
            var idRecipies = $("#IdRecipies").val();
            var batchS = $("#BatchSize").val();
            //alert(idRecipies + " AAA " + batchS);
            $("#partialIngredientsToSubstract").load('@(Url.Action("_Index", "IngredientsToSubstract", null, Request.Url.Scheme))?recipiesID=' + idRecipies + "&batchSize=" + batchS);
        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Brews</h4>
    <hr />
    <br />
    <h3>Recipies of the day in base of available Ingredients</h3>
    <div id="partialRecipiesOfTheDay" style="border: 1px solid;">
        @Html.Action("_Index", new { Controller = "RecipiesOfTheDay", action = "_Index" })
    </div>
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BatchSize, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BatchSize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BatchSize, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdRecipies, "IdRecipies", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IdRecipies", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdRecipies, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateBrew, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateBrew, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateBrew, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    <br />
    <div id="partialIngredientsToSubstract" style="border: 1px solid;">
    </div>
    <br />
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BrewDayAPP/Views/Brews/Delete.cshtml
@model BrewDayAPP.Brews

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brews</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BatchSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BatchSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateBrew)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateBrew)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Recipies.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Recipies.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BrewDayAPP/Views/Brews/Details.cshtml
@model BrewDayAPP.Brews

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Brews</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BatchSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BatchSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateBrew)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateBrew)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Recipies.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Recipies.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BrewDayAPP/Views/Brews/Edit.cshtml
@model BrewDayAPP.Brews

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brews</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdRecipies, "IdRecipies", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdRecipies", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdRecipies, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatchSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BatchSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BatchSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateBrew, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateBrew, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateBrew, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BrewDayAPP/Views/Brews/Index.cshtml
@model IEnumerable<BrewDayAPP.Brews>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BatchSize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateBrew)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Recipies.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BatchSize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateBrew)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUsers.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recipies.Description)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |*@
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>